### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by yochananmarqos** [Bitsteward/bitsteward#16]
I normally unlock my vault first with `bw unlock <password>`, however with the recent changes Bitsteward no longer launches whether I do that or not:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bitsteward/src/main.py", line 233, in on_activate
    win = AppWindow(app)
  File "/usr/lib/python3.10/site-packages/bitsteward/src/main.py", line 34, in __init__
    self.init_ui()
  File "/usr/lib/python3.10/site-packages/bitsteward/src/main.py", line 83, in init_ui
    self.load_vault_folders()
  File "/usr/lib/python3.10/site-packages/bitsteward/src/main.py", line 145, in load_vault_folders
    vault_folders_json = Server.get_vault_folders()
  File "/usr/lib/python3.10/site-packages/bitsteward/src/utility/server_requests.py", line 35, in get_vault_folders
    output, _ = p.communicate(input=bw_password.encode())
AttributeError: 'NoneType' object has no attribute 'encode'
Syncing complete.
```

**Comment by mxmvncnt** [comment]
Hello, from what I understand, python could not find your password string inside the `.env` file. Until I use the integration with the systems Keyring, it is needed to have the password stored in the .env file with the BW_PASSWORD variable, in this format:
```
BW_PASSWORD="password123"
```
The old BW_SESSION is not needed anymore. Be aware this file visible to your entire system, so you should really not store your real bitwarden vault password in there

**Comment by yochananmarqos** [comment]
> the .env file

Where is that supposed to reside?

**Comment by mxmvncnt** [comment]
> Where is that supposed to reside? The same place as the `bw` binary?

Yes, basically under `.../bitsteward/.env`. You should already have that file created if you used the old installation instructions, since I just changed what should be inside the file

**Comment by yochananmarqos** [comment]
No, I never did as it was always installed in a read-only location. I'll see how I can get that to work.

**Comment by yochananmarqos** [comment]
I implemented it by [packaging an empty `.env` file,](https://github.com/yochananmarqos/pkgbuilds/commit/a4677e42f271862f499966719f033097bbaec8f1) it will have to do for now.
